// Re‑exported from the unified date‑range module for backward compatibility.
// Prefer importing from `@/lib/date-range` for new code.
export {
  ymd,
  parseYmd,
  addDays,
  daysBetween,
  spanDays,
  inRange,
  ymOffset,
  currentMonth,
  monthFullLabel,
  monthBounds,
  asCalendarMonth,
  type DateRange,
  type RangePreset,
  type PresetKey,
  type Granularity,
  type Bucket,
  type Period,
  RANGE_PRESETS,
  PRESETS,
  presetRange,
  resolvePeriod,
  granularityFor,
  enumerateBuckets,
  bucketKeyForDate,
  bucketRange,
  useDateRange as useSpendPeriod,
} from "../date-range";
