import {
  AlertTriangle,
  ArrowLeftRight,
  Banknote,
  BarChart3,
  Bell,
  CalendarClock,
  Cable,
  Car,
  Camera,
  ChevronLeft,
  ChevronRight,
  Clapperboard,
  FileText,
  Info,
  PenLine,
  Plus,
  GraduationCap,
  Globe,
  HeartPulse,
  Home,
  Landmark,
  LineChart,
  ListChecks,
  LogOut,
  PieChart,
  PiggyBank,
  Plane,
  Receipt,
  RefreshCw,
  Repeat,
  Search,
  Settings,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Tag,
  Trash2,
  TrendingDown,
  TrendingUp,
  Utensils,
  Wallet,
  Zap,
  type LucideIcon,
} from "lucide-react";

export {
  AlertTriangle,
  ArrowLeftRight,
  BarChart3,
  Bell,
  CalendarClock,
  Cable,
  Camera,
  ChevronLeft,
  ChevronRight,
  FileText,
  Globe,
  Home,
  Info,
  Landmark,
  ListChecks,
  LogOut,
  LineChart,
  PenLine,
  PieChart,
  Plus,
  RefreshCw,
  Search,
  Settings,
  Sparkles,
  Repeat,
  Trash2,
  TrendingDown,
  TrendingUp,
  Wallet,
  Zap,
};

/** Summary rows (Dashboard §7.1). */
export const SUMMARY_ICONS = {
  income: TrendingUp,
  spending: TrendingDown,
  savings: PiggyBank,
} as const;

/** Category name -> icon (§7.1). Case-insensitive substring match; fallback Tag. */
const CATEGORY_ICONS: Array<[RegExp, LucideIcon]> = [
  [/rent|mortgage/i, Landmark],
  [/hous/i, Home],
  [/grocer/i, ShoppingCart],
  [/dining|restaurant/i, Utensils],
  [/utilit/i, Zap],
  [/transport|fuel/i, Car],
  [/health/i, HeartPulse],
  [/shopping/i, ShoppingBag],
  [/travel/i, Plane],
  [/entertain/i, Clapperboard],
  [/education/i, GraduationCap],
  [/salary|income/i, Banknote],
  [/transfer/i, ArrowLeftRight],
  [/fee/i, Receipt],
  [/subscription/i, RefreshCw],
];

export function categoryIcon(name: string | null | undefined): LucideIcon {
  if (!name) return Tag;
  for (const [re, icon] of CATEGORY_ICONS) if (re.test(name)) return icon;
  return Tag;
}
