"""M1 initial schema

Revision ID: 9017a6324a24
Revises: 
Create Date: 2026-06-14 12:56:31.564678
"""
from typing import Sequence, Union

import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = '9017a6324a24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector extension must exist before the guidance_doc.embedding column.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rate',
    sa.Column('currency_pair', sa.String(length=7), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.PrimaryKeyConstraint('currency_pair', 'date', name=op.f('pk_fx_rate'))
    )
    op.create_table('guidance_doc',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('topic', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_type', sa.Enum('govt', 'community', 'other', name='guidance_source_type', native_enum=False), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guidance_doc'))
    )
    op.create_table('household',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household'))
    )
    op.create_table('category',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.Enum('category', 'subcategory', 'item_type', name='category_kind', native_enum=False), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_category_household_id_household'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], name=op.f('fk_category_parent_id_category'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    op.create_index(op.f('ix_category_household_id'), 'category', ['household_id'], unique=False)
    op.create_table('plaid_item',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('access_token_encrypted', sa.String(length=1024), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_plaid_item_household_id_household'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plaid_item'))
    )
    op.create_index(op.f('ix_plaid_item_household_id'), 'plaid_item', ['household_id'], unique=False)
    op.create_table('rule',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('matcher', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('user', 'system', name='rule_source', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_rule_household_id_household'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule'))
    )
    op.create_index(op.f('ix_rule_household_id'), 'rule', ['household_id'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_tag_household_id_household'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag'))
    )
    op.create_index(op.f('ix_tag_household_id'), 'tag', ['household_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=True),
    sa.Column('role', sa.Enum('owner', 'member', 'viewer', name='user_role', native_enum=False), nullable=False),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_user_household_id_household'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_index(op.f('ix_user_household_id'), 'user', ['household_id'], unique=False)
    op.create_table('account_logical',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('checking', 'savings', 'credit', 'cash', 'loan', 'investment', name='account_type', native_enum=False), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('mask', sa.String(length=16), nullable=True),
    sa.Column('plaid_item_id', sa.UUID(), nullable=True),
    sa.Column('plaid_account_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_account_logical_household_id_household'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], name=op.f('fk_account_logical_owner_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plaid_item_id'], ['plaid_item.id'], name=op.f('fk_account_logical_plaid_item_id_plaid_item'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_logical'))
    )
    op.create_index(op.f('ix_account_logical_household_id'), 'account_logical', ['household_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity', sa.String(length=128), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], name=op.f('fk_audit_log_actor_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_audit_log_household_id_household'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_household_id'), 'audit_log', ['household_id'], unique=False)
    op.create_table('bot_link',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('telegram', 'discord', name='bot_platform', native_enum=False), nullable=False),
    sa.Column('platform_user_id', sa.String(length=128), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('consent', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_bot_link_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_link'))
    )
    op.create_index(op.f('ix_bot_link_user_id'), 'bot_link', ['user_id'], unique=False)
    op.create_table('budget',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('period', sa.Enum('monthly', 'quarterly', 'yearly', name='budget_period', native_enum=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_budget_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_budget_household_id_household'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget'))
    )
    op.create_index(op.f('ix_budget_household_id'), 'budget', ['household_id'], unique=False)
    op.create_table('consent_record',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('sms', 'email', 'bot', 'plaid', name='consent_channel', native_enum=False), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_consent_record_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent_record'))
    )
    op.create_index(op.f('ix_consent_record_user_id'), 'consent_record', ['user_id'], unique=False)
    op.create_table('cross_border_transfer',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.Enum('out', 'in', name='transfer_direction', native_enum=False), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.String(length=128), nullable=True),
    sa.Column('transfer_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_cross_border_transfer_household_id_household'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], name=op.f('fk_cross_border_transfer_owner_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cross_border_transfer'))
    )
    op.create_index(op.f('ix_cross_border_transfer_household_id'), 'cross_border_transfer', ['household_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('type', sa.Enum('receipt', 'statement', 'paystub', 'invoice', 'csv', 'other', name='document_type', native_enum=False), nullable=False),
    sa.Column('source_channel', sa.Enum('upload', 'email', 'sms', 'bot', 'plaid', 'manual', name='document_source_channel', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'needs_review', 'processed', 'failed', name='document_status', native_enum=False), nullable=False),
    sa.Column('ocr_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_document_household_id_household'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['user.id'], name=op.f('fk_document_uploaded_by_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document'))
    )
    op.create_index(op.f('ix_document_household_id'), 'document', ['household_id'], unique=False)
    op.create_table('income_source',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('employer', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('frequency', sa.Enum('weekly', 'biweekly', 'semimonthly', 'monthly', 'annual', name='income_frequency', native_enum=False), nullable=False),
    sa.Column('gross', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('withholding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_income_source_household_id_household'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], name=op.f('fk_income_source_owner_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_income_source'))
    )
    op.create_index(op.f('ix_income_source_household_id'), 'income_source', ['household_id'], unique=False)
    op.create_table('llm_usage_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_est', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('purpose', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_llm_usage_log_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage_log'))
    )
    op.create_table('loan',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('credit_card', 'personal', 'auto', 'education', 'home', 'other', name='loan_type', native_enum=False), nullable=False),
    sa.Column('schedule_kind', sa.Enum('revolving', 'amortizing', 'emi', name='loan_schedule_kind', native_enum=False), nullable=False),
    sa.Column('principal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('compounding', sa.Enum('monthly', 'daily', name='loan_compounding', native_enum=False), nullable=True),
    sa.Column('min_or_emi_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('penalty_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_loan_household_id_household'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], name=op.f('fk_loan_owner_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loan'))
    )
    op.create_index(op.f('ix_loan_household_id'), 'loan', ['household_id'], unique=False)
    op.create_table('merchant',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_category_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['default_category_id'], ['category.id'], name=op.f('fk_merchant_default_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_merchant_household_id_household'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant'))
    )
    op.create_index(op.f('ix_merchant_household_id'), 'merchant', ['household_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('channel', sa.Enum('push', 'email', 'inapp', 'bot', name='notification_channel', native_enum=False), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', 'read', name='notification_status', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_notification_household_id_household'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notification_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_index(op.f('ix_notification_household_id'), 'notification', ['household_id'], unique=False)
    op.create_table('recommendation',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supporting_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_recommendation_household_id_household'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_recommendation_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation'))
    )
    op.create_index(op.f('ix_recommendation_household_id'), 'recommendation', ['household_id'], unique=False)
    op.create_table('refresh_token',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_refresh_token_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token'))
    )
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    op.create_table('equity_grant',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('income_source_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('rsu', 'espp', 'iso', 'nso', name='equity_grant_type', native_enum=False), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('grant_date', sa.Date(), nullable=True),
    sa.Column('shares', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('strike_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('vesting_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['income_source_id'], ['income_source.id'], name=op.f('fk_equity_grant_income_source_id_income_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equity_grant'))
    )
    op.create_index(op.f('ix_equity_grant_income_source_id'), 'equity_grant', ['income_source_id'], unique=False)
    op.create_table('payment_schedule',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('installment_no', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal_component', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('interest_component', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.Enum('due', 'paid', 'late', name='payment_status', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], name=op.f('fk_payment_schedule_loan_id_loan'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_schedule'))
    )
    op.create_index(op.f('ix_payment_schedule_loan_id'), 'payment_schedule', ['loan_id'], unique=False)
    op.create_table('paystub',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('income_source_id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('gross', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('deductions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('net', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['income_source_id'], ['income_source.id'], name=op.f('fk_paystub_income_source_id_income_source'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['document.id'], name=op.f('fk_paystub_source_document_id_document'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paystub'))
    )
    op.create_index(op.f('ix_paystub_income_source_id'), 'paystub', ['income_source_id'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'confirmed', name='transaction_status', native_enum=False), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('source_channel', sa.String(length=32), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_logical.id'], name=op.f('fk_transaction_account_id_account_logical'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_transaction_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_transaction_household_id_household'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_transaction_merchant_id_merchant'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], name=op.f('fk_transaction_owner_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['document.id'], name=op.f('fk_transaction_source_document_id_document'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction')),
    sa.UniqueConstraint('source_channel', 'external_id', name='uq_transaction_source_external')
    )
    op.create_index(op.f('ix_transaction_household_id'), 'transaction', ['household_id'], unique=False)
    op.create_table('equity_event',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('equity_grant_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('vest', 'purchase', 'sale', name='equity_event_type', native_enum=False), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('shares', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('fmv', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('proceeds', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('est_tax', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['equity_grant_id'], ['equity_grant.id'], name=op.f('fk_equity_event_equity_grant_id_equity_grant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equity_event'))
    )
    op.create_index(op.f('ix_equity_event_equity_grant_id'), 'equity_event', ['equity_grant_id'], unique=False)
    op.create_table('line_item',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('item_type_category_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['item_type_category_id'], ['category.id'], name=op.f('fk_line_item_item_type_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name=op.f('fk_line_item_transaction_id_transaction'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_line_item'))
    )
    op.create_index(op.f('ix_line_item_transaction_id'), 'line_item', ['transaction_id'], unique=False)
    op.create_table('transaction_tag',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_transaction_tag_tag_id_tag'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name=op.f('fk_transaction_tag_transaction_id_transaction'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id', 'tag_id', name=op.f('pk_transaction_tag'))
    )
    op.create_table('line_item_tag',
    sa.Column('line_item_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['line_item_id'], ['line_item.id'], name=op.f('fk_line_item_tag_line_item_id_line_item'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_line_item_tag_tag_id_tag'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('line_item_id', 'tag_id', name=op.f('pk_line_item_tag'))
    )
    # ### end Alembic commands ###

    _seed_taxonomy_and_merchants()


# --- M1 seeds ------------------------------------------------------------
# Stable UUIDs derived from names so re-running against a fresh DB is
# reproducible and merchants can reference categories by id.
_NS = uuid.UUID("00000000-0000-0000-0000-0000000c0de5")


def _cat_id(name: str) -> uuid.UUID:
    return uuid.uuid5(_NS, f"category:{name}")


# Starter taxonomy: top-level categories, each with subcategories. A handful
# of "item_type" categories support line-item (receipt) classification.
_TAXONOMY: dict[str, list[str]] = {
    "Income": ["Salary", "Bonus", "Interest", "Dividends", "Refunds"],
    "Food & Dining": ["Restaurants", "Coffee Shops", "Fast Food", "Alcohol & Bars"],
    "Groceries": [],
    "Shopping": ["Clothing", "Electronics", "Home & Furniture", "Hobbies"],
    "Transportation": ["Fuel", "Public Transit", "Rideshare", "Parking", "Auto Maintenance"],
    "Housing": ["Rent", "Mortgage", "Property Tax", "Home Maintenance"],
    "Utilities": ["Electricity", "Water", "Gas", "Internet", "Mobile Phone"],
    "Health & Medical": ["Doctor", "Pharmacy", "Dental", "Insurance Premiums"],
    "Entertainment": ["Streaming", "Movies & Events", "Games", "Subscriptions"],
    "Travel": ["Flights", "Hotels", "Car Rental"],
    "Education": ["Tuition", "Books & Supplies", "Courses"],
    "Personal Care": ["Salon & Spa", "Gym & Fitness", "Cosmetics"],
    "Financial": ["Bank Fees", "Interest Charges", "Investments", "Taxes"],
    "Transfers": ["Cross-Border Transfer", "Internal Transfer", "Credit Card Payment"],
    "Gifts & Donations": [],
    "Business": ["Office Supplies", "Software", "Travel & Meals"],
    "Miscellaneous": [],
}

# Item types for receipt line items (kind='item_type').
_ITEM_TYPES = [
    "Apparel", "Cosmetics", "Electronics Item", "Grocery Item",
    "Household Item", "Toy", "Book", "Food Item", "Beverage",
]

# Common global merchants → default category (canonical_name, aliases, category).
_MERCHANTS = [
    ("Amazon", ["amazon.com", "amzn", "amazon mktp"], "Shopping"),
    ("Walmart", ["wal-mart", "walmart.com"], "Groceries"),
    ("Target", ["target.com"], "Shopping"),
    ("Costco", ["costco whse"], "Groceries"),
    ("Macy's", ["macys", "macy s"], "Shopping"),
    ("Starbucks", ["sbux"], "Food & Dining"),
    ("McDonald's", ["mcdonalds"], "Food & Dining"),
    ("Uber", ["uber trip", "uber eats"], "Transportation"),
    ("Lyft", [], "Transportation"),
    ("Netflix", ["netflix.com"], "Entertainment"),
    ("Spotify", ["spotify"], "Entertainment"),
    ("Apple", ["apple.com/bill", "itunes"], "Shopping"),
    ("Google", ["google *", "google services"], "Entertainment"),
    ("Shell", ["shell oil"], "Transportation"),
    ("Whole Foods", ["whole foods market", "wfm"], "Groceries"),
    ("Flipkart", ["flipkart.com"], "Shopping"),
    ("Swiggy", [], "Food & Dining"),
    ("Zomato", [], "Food & Dining"),
    ("Reliance Fresh", ["reliance retail"], "Groceries"),
    ("BigBasket", ["bigbasket.com"], "Groceries"),
]


def _seed_taxonomy_and_merchants() -> None:
    category = sa.table(
        "category",
        sa.column("id", sa.UUID()),
        sa.column("household_id", sa.UUID()),
        sa.column("parent_id", sa.UUID()),
        sa.column("name", sa.String()),
        sa.column("kind", sa.String()),
        sa.column("is_system", sa.Boolean()),
    )
    merchant = sa.table(
        "merchant",
        sa.column("id", sa.UUID()),
        sa.column("household_id", sa.UUID()),
        sa.column("canonical_name", sa.String()),
        sa.column("aliases", postgresql.JSONB()),
        sa.column("default_category_id", sa.UUID()),
    )

    cat_rows = []
    for top, subs in _TAXONOMY.items():
        cat_rows.append({
            "id": _cat_id(top), "household_id": None, "parent_id": None,
            "name": top, "kind": "category", "is_system": True,
        })
        for sub in subs:
            cat_rows.append({
                "id": _cat_id(f"{top}/{sub}"), "household_id": None,
                "parent_id": _cat_id(top), "name": sub,
                "kind": "subcategory", "is_system": True,
            })
    for it in _ITEM_TYPES:
        cat_rows.append({
            "id": _cat_id(f"item_type/{it}"), "household_id": None,
            "parent_id": None, "name": it, "kind": "item_type", "is_system": True,
        })
    op.bulk_insert(category, cat_rows)

    merch_rows = [
        {
            "id": uuid.uuid5(_NS, f"merchant:{name}"), "household_id": None,
            "canonical_name": name, "aliases": aliases,
            "default_category_id": _cat_id(cat),
        }
        for name, aliases, cat in _MERCHANTS
    ]
    op.bulk_insert(merchant, merch_rows)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('line_item_tag')
    op.drop_table('transaction_tag')
    op.drop_index(op.f('ix_line_item_transaction_id'), table_name='line_item')
    op.drop_table('line_item')
    op.drop_index(op.f('ix_equity_event_equity_grant_id'), table_name='equity_event')
    op.drop_table('equity_event')
    op.drop_index(op.f('ix_transaction_household_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_paystub_income_source_id'), table_name='paystub')
    op.drop_table('paystub')
    op.drop_index(op.f('ix_payment_schedule_loan_id'), table_name='payment_schedule')
    op.drop_table('payment_schedule')
    op.drop_index(op.f('ix_equity_grant_income_source_id'), table_name='equity_grant')
    op.drop_table('equity_grant')
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_recommendation_household_id'), table_name='recommendation')
    op.drop_table('recommendation')
    op.drop_index(op.f('ix_notification_household_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_merchant_household_id'), table_name='merchant')
    op.drop_table('merchant')
    op.drop_index(op.f('ix_loan_household_id'), table_name='loan')
    op.drop_table('loan')
    op.drop_table('llm_usage_log')
    op.drop_index(op.f('ix_income_source_household_id'), table_name='income_source')
    op.drop_table('income_source')
    op.drop_index(op.f('ix_document_household_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_cross_border_transfer_household_id'), table_name='cross_border_transfer')
    op.drop_table('cross_border_transfer')
    op.drop_index(op.f('ix_consent_record_user_id'), table_name='consent_record')
    op.drop_table('consent_record')
    op.drop_index(op.f('ix_budget_household_id'), table_name='budget')
    op.drop_table('budget')
    op.drop_index(op.f('ix_bot_link_user_id'), table_name='bot_link')
    op.drop_table('bot_link')
    op.drop_index(op.f('ix_audit_log_household_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_account_logical_household_id'), table_name='account_logical')
    op.drop_table('account_logical')
    op.drop_index(op.f('ix_user_household_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tag_household_id'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_rule_household_id'), table_name='rule')
    op.drop_table('rule')
    op.drop_index(op.f('ix_plaid_item_household_id'), table_name='plaid_item')
    op.drop_table('plaid_item')
    op.drop_index(op.f('ix_category_household_id'), table_name='category')
    op.drop_table('category')
    op.drop_table('household')
    op.drop_table('guidance_doc')
    op.drop_table('fx_rate')
    # ### end Alembic commands ###
